name: diogolara
favicon: null
layout_spectrum: 0.9233201693277806
typography_spectrum: 0.3842652786988765
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#100e11'
    - '#beb096'
    - '#af8648'
    - '#7e4a32'
    - '#8a6e49'
  brandStrength: 0.4994078120216727
  lightness: 0.37620325898751616
  saturation: 0.875
  rhythmicContrast: 0.3364079419989139
purpose: []
